[workspace]
[package]
version = "0.1.0"
name = "sp1-helios-primitives"
edition = "2021"

[dependencies]
eyre = "0.6.8"
ssz-rs = { package = "ssz_rs", version = "0.9.0" }
hex = "0.4.3"
serde_with = { version = "3.4.0", features = ["hex"] }
serde = { version = "1.0.195", features = ["derive"] }
serde_json = "1.0.11"
common = { path = "../../helios/common"}
alloy-sol-types = "0.7.7"
alloy-primitives = { version = "0.7.7", features = ["serde"] }

[patch.crates-io]
sha2-v0-9-9 = { git = "https://github.com/sp1-patches/RustCrypto-hashes", package = "sha2", branch = "patch-sha2-v0.9.9" }
sha2-v0-10-8 = { git = "https://github.com/sp1-patches/RustCrypto-hashes", package = "sha2", branch = "patch-sha2-v0.10.8" }
tiny-keccak = { git = "https://github.com/sp1-patches/tiny-keccak", branch = "patch-v2.0.2" }
